spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ms-email-ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: amqps://jaragua.lmq.cloudamqp.com
    username: ndwssdvc
    password: g7uMLiyz5fCPjN9hvIzXX2kgBb-pvUzA
    virtual-host: ndwssdvc


server:
  port: 8080